#!/usr/bin/env bash
#
# Seeds some data in Vault for vault-agent
# uses the Georgesre structure

## Following files, for SCRIPT_DIR warnings
# shellcheck disable=SC1090

set -e

shopt -s expand_aliases

SCRIPT_DIR="$( cd "$( dirname "$0" )" && pwd )"
source "${SCRIPT_DIR}/variables.sh"
source "${SCRIPT_DIR}/functions.sh"

echo "Checking that Minikube is installed and running"
ensure_minikube_installed_and_running "$MINIKUBE_VERSION" "$BUILD_PLATFORM" "$KUBERNETES_VERSION"

echo "Making sure Kubernetes is running"
ensure_kubernetes_running

run_vault write secret/projects/georgesreinc-test/services/foo/defaults/test1 value=value1
run_vault write secret/projects/georgesreinc-test/services/bar/defaults/test1 value=value1
run_vault write secret/projects/georgesreinc-test/services/bar/defaults/test2 value=value2
run_vault write secret/projects/georgesreinc-test/services/baz/namespaces/ops/apikey value=secret

kubectl create namespace ops
kubectl create namespace stable
kubectl create namespace all-apps
kubectl create namespace foo
kubectl create namespace wrong
kubectl apply -f - <<-EOF
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-agent.app-config
  namespace: ops
data:
  apps: |-
    - baz
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-agent.app-config
  namespace: all-apps
data:
  apps: ALL
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-agent.app-config
  namespace: foo
data:
  apps: foo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-agent.app-config
  namespace: wrong
data:
  apps: |-
    - baz
    - ALL
EOF
