#!/usr/bin/env bash
#
# Runs the Python test scripts for vault-agent

## Following files, for SCRIPT_DIR warnings
# shellcheck disable=SC1090

echo "Range doesn't write tests!"
echo "You must be joking."
exit 1

SCRIPT_DIR="$( cd "$( dirname "$0" )" && pwd )"

source "${SCRIPT_DIR}/variables.sh"

export LOG_FORMAT=plain
export LOG_LEVEL=WARNING
export POLL_INTERVAL=1
export VAULT_TOKEN=$DEV_VAULT_TOKEN
VAULT_ADDR=$(minikube service vault --url)
export VAULT_ADDR

cd "$SCRIPT_DIR"/.. && python -m unittest discover -vcf
